---
name: "Mirror"
on:
  workflow_dispatch:
  schedule:
    - cron: "37 * * * *"

defaults:
  run:
    shell: bash

env:
  DOCKER_BUILDKIT: 1

permissions: read-all

jobs:
  lookup:
    runs-on: ubuntu-latest
    name: Perform mirroring
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false

    steps:
      - name: Configure Git to use HTTPS with the PAT
        run: |
          git config --global url."https://${{ secrets.GH_PUBLIC_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.GH_PUBLIC_TOKEN }}@github.com".insteadOf "ssh://git@github.com"
          git config --global advice.detachedHead false
          git config --global user.name "NWL Bot"
          git config --global user.email "bot@northwood-labs.com"

      - name: Sync go.googlesource.com/perf → github.com/northwood-labs/go-x-perf
        run: |
          git clone --bare "https://go.googlesource.com/perf" ".goxperf"
          cd ".goxperf" && git push --force --mirror "https://github.com/northwood-labs/go-x-perf.git"
          git clone "https://github.com/northwood-labs/go-x-perf.git" "${{ github.workspace }}/go-x-perf"

      - name: Tag
        working-directory: "${{ github.workspace }}/go-x-perf"
        run: |
          COMMIT_DATE="$(git log -1 --format="%at")"
          YY=$(date -d @$COMMIT_DATE +%Y)
          MM=$(( $(date -d @$COMMIT_DATE +%m) ))
          DD=$(( $(date -d @$COMMIT_DATE +%d) ))

          git tag "${YY}.${MM}.${DD}" && \
          git push --tags "https://github.com/northwood-labs/go-x-perf.git"
